package dev.sdlc.factory.app.initialization;

import dev.sdlc.factory.common.ContentHash;
import dev.sdlc.factory.runner.ProjectRunner;
import dev.sdlc.factory.runner.RunnerCommand;
import dev.sdlc.factory.runner.RunnerOutput;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.Duration;
import java.util.List;
import java.util.LinkedHashMap;
import java.util.Map;

/** 固定版本的纯 Node 脚手架模板；命令由已发布模板定义，不接受请求方注入。 */
public final class NodeTemplateAdapter {

    public static final String ID = "TPL-NODE-BASIC";
    public static final String VERSION = "1.0.0";
    private static final String DESCRIPTOR = "protocol=1.1;template=TPL-NODE-BASIC@1.0.0;runtime=node>=22";

    private final ProjectRunner runner;

    public NodeTemplateAdapter(ProjectRunner runner) {
        this.runner = runner;
    }

    public String digest() {
        return ContentHash.ofSha256(DESCRIPTOR).canonical();
    }

    public void instantiate(Path workspace, String projectName) throws IOException {
        Files.createDirectories(workspace.resolve("src"));
        Files.createDirectories(workspace.resolve("test"));
        Files.createDirectories(workspace.resolve("scripts"));
        Files.createDirectories(workspace.resolve(".factory/evidence"));
        Files.writeString(workspace.resolve("package.json"), packageJson(projectName));
        Files.writeString(workspace.resolve("src/server.js"), serverJs());
        Files.writeString(workspace.resolve("test/server.test.js"), testJs());
        Files.writeString(workspace.resolve("scripts/runtime-cycle.js"), runtimeCycleJs());
        Files.writeString(workspace.resolve("README.md"), "# " + projectName + "\n\nGenerated by SDLC Factory.\n");
    }

    public RunnerOutput bootstrap(Path workspace) {
        run(workspace, List.of("git", "init"), Duration.ofSeconds(20));
        run(workspace, List.of("git", "add", "."), Duration.ofSeconds(20));
        return run(workspace, List.of("git", "-c", "user.name=SDLC Factory", "-c",
                "user.email=factory@localhost", "commit", "-m", "初始化项目"), Duration.ofSeconds(30));
    }

    public String revision(Path workspace) {
        return requireSuccess("git revision", run(workspace, List.of("git", "rev-parse", "HEAD"),
                Duration.ofSeconds(10))).stdout().trim();
    }

    public Map<String, RunnerOutput> validate(Path workspace) {
        Map<String, RunnerOutput> results = new LinkedHashMap<>();
        results.put("VALIDATE", run(workspace, List.of("node", "--check", "src/server.js"), Duration.ofSeconds(20)));
        results.put("COMPILE", run(workspace, List.of("node", "--check", "src/server.js"), Duration.ofSeconds(20)));
        results.put("BUILD", run(workspace, List.of("node", "--check", "scripts/runtime-cycle.js"), Duration.ofSeconds(20)));
        results.put("TEST", run(workspace, List.of("node", "--test"), Duration.ofSeconds(30)));
        results.put("RUNTIME_CYCLE", run(workspace, List.of("node", "scripts/runtime-cycle.js"), Duration.ofSeconds(30)));
        return results;
    }

    public RunnerOutput requireSuccess(String operation, RunnerOutput output) {
        if (output.timedOut() || output.exitCode() != 0) {
            throw new IllegalStateException(operation + " 失败：" + output.stderr());
        }
        return output;
    }

    private RunnerOutput run(Path workspace, List<String> command, Duration timeout) {
        return runner.execute(new RunnerCommand(command, workspace, Map.of(), timeout));
    }

    private String packageJson(String name) {
        String safe = name.toLowerCase().replaceAll("[^a-z0-9-]+", "-").replaceAll("(^-|-$)", "");
        if (safe.isBlank()) safe = "factory-project";
        return """
                {"name":"%s","version":"0.1.0","private":true,"type":"module",
                 "scripts":{"compile":"node --check src/server.js","build":"node --check src/server.js",
                 "test":"node --test","start":"node src/server.js"}}
                """.formatted(safe);
    }

    private String serverJs() {
        return """
                import http from 'node:http';
                import { fileURLToPath } from 'node:url';
                export const createServer = () => http.createServer((request, response) => {
                  response.writeHead(200, { 'content-type': 'application/json' });
                  response.end(JSON.stringify({ status: 'UP' }));
                });
                if (process.argv[1] === fileURLToPath(import.meta.url)) {
                  const server = createServer();
                  server.listen(Number(process.env.PORT || 0), '127.0.0.1', () => {
                    console.log(`READY:${server.address().port}`);
                  });
                }
                """;
    }

    private String testJs() {
        return """
                import test from 'node:test';
                import assert from 'node:assert/strict';
                import { createServer } from '../src/server.js';
                test('readiness', async () => {
                  const server = createServer();
                  await new Promise(resolve => server.listen(0, '127.0.0.1', resolve));
                  const response = await fetch(`http://127.0.0.1:${server.address().port}`);
                  assert.deepEqual(await response.json(), { status: 'UP' });
                  await new Promise(resolve => server.close(resolve));
                });
                """;
    }

    private String runtimeCycleJs() {
        return """
                import { spawn } from 'node:child_process';
                const child = spawn(process.execPath, ['src/server.js'], { env: { ...process.env, PORT: '0' } });
                let output = '';
                child.stdout.on('data', chunk => { output += chunk; });
                const deadline = Date.now() + 10000;
                while (!output.includes('READY:') && Date.now() < deadline) await new Promise(r => setTimeout(r, 50));
                const port = Number(output.match(/READY:(\\d+)/)?.[1]);
                if (!port) { child.kill(); throw new Error('server readiness timeout'); }
                const response = await fetch(`http://127.0.0.1:${port}`);
                if (!response.ok || (await response.json()).status !== 'UP') throw new Error('readiness failed');
                child.kill();
                await new Promise(resolve => child.once('exit', resolve));
                console.log(JSON.stringify({ start: 'SUCCEEDED', readiness: 'READY', stop: 'SUCCEEDED', port }));
                """;
    }
}
